runtime: nodejs
service: hello-world
env: flex
automatic_scaling:
    cool_down_period_sec: 180
    cpu_utilization:
        target_utilization: 0.9
resources:
    cpu: 1
    memory_gb: 1
    disk_size_gb: 10
readiness_check:
  app_start_timeout_sec: 1800