name: Hello World Deploy

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deployment:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Deploy Hello World App
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          project_id: "lionstep-europe-dev"
          credentials: ${{ secrets.GCP_SA_KEY }}
          promote: true
